### PR TITLE
Update the example environment variable names

### PR DESCRIPTION
**Pull request by plule**
Some environment variables names aren't up to date in the examples.

Not sure about DEFAULT_SERVER_NAME, should it be NAME?

### CODE REVIEW

**Comment by thasmo** [comment]
Hey, thanks a lot for contributing! Yes, `DEFAULT_SERVER_NAME` should be `NAME` - would you mind updating your PR? Thanks!

**Comment by thasmo** [comment]
Thanks for your contribution! 👍

**Comment by plule** [comment]
@thasmo ahah, got your message at work, you beat me :)

Thank you for this docker image, it's really well done and documented!

**Comment by thasmo** [comment]
Thanks for the contribution and your feedback. Keep 'em coming if you like, we'd love to get more feedback. :)

**Pull request merged**
