### PR TITLE
Create a new Dockerfile for modded servers #67 

### PR DESCRIPTION
**Pull request by BraisGabin**
This doesn't work right now, it's just an example for #67.

If you want a modded server you need to use this Dockerfile and set the `ARG` `MODS`.

### CODE REVIEW

**Comment by thasmo** [comment]
Would it be possible to bake this into the current Dockerfile?

**Comment by BraisGabin** [comment]
It would be possible. But if it's all in the same Dockerfile you must build all the image. If it's a different image you can dowload the game and just build the modded part.

**Comment by thasmo** [comment]
@BraisGabin Be sure to checkout [ONBUILD](https://docs.docker.com/engine/reference/builder/#/onbuild), which, I guess, could make things a lot easier.

**Comment by BraisGabin** [comment]
This PR is far too old and simple so I'm going to start it form scratch again. Closing...

**Pull request closed without merging**
