### PR TITLE
Stop the server cleanly and fix the console attach. Close #19 and Fix #41

### LINKED ISSUE #19: Trap the signals
It seems that `dontstarve_dedicated_server_nullrenderer` don't react preaty well to the signals. If we write `c_shutdown(true)` at the game console we get this nice log:

```
c_shutdown(true)
ConsoleInput: "c_shutdown(true)"
c_shutdown      true
Serializing world: session/F79FF192BBBCB9EC/0000000003
Could not unload undefined prefab 0x1872ccf0 (FROMNUM)
Updates 0Seconds elapsed: 14.4339 fps:0
[Steam] UserDisconnect successfully sent for steamid ''
Collecting garbage...
lua_gc took 0.11 seconds
~ShardLuaProxy()
~InventoryLuaProxy()
~NetworkLuaProxy()
~SimLuaProxy()
lua_close took 0.15 seconds
CurlRequestManager::ClientThread::Main() complete
HttpClient2 discarded 1 callbacks.
Shutting down
```

If we just send a `Ctrl + C` signal there isn't any new line in the log :cry:

So, we need to trap this signals and send to the `dontstarve_dedicated_server_nullrenderer` the proper commands to close cleanly.

We must investigate if `c_shutdown(true)` is the best option. I opened a topic to ask about this: http://forums.kleientertainment.com/topic/62055-which-is-the-cleanest-way-to-stop-a-dst-server/

Some links provided by @thasmo about how to deal with the signals:
- https://rimuhosting.com/knowledgebase/linux/misc/trapping-ctrl-c-in-bash
- http://hacktux.com/bash/control/c
- http://redsymbol.net/articles/bash-exit-traps/
- http://ubuntuforums.org/showthread.php?t=1546996

### LINKED ISSUE #41: docker attach don't allow to write in the console directly
Right now the only way to write in the console is using `dst-server console`. The reason is because we are redirecting `stdin`. We need to fix this.

### PR DESCRIPTION
**Pull request by BraisGabin**
Close the server nicely.

### CODE REVIEW

**Comment by thasmo** [comment]
Do you think there's any solution to run the nullrenderer not in the background? If not, we skip this feature completely and request proper signal handling at Klei.

**Comment by BraisGabin** [comment]
No, we must run it in background. But what is what you don't like about this solution exactly? Because there are somethings that can be fixed.

I think that a good close is a really important feature. Right now `docker stop` sends a `SIGTERM` that the dst ignores and 10 seconds later it send a `SIGKILL`. So right now we are doing it poorly.

**Comment by thasmo** [comment]
Actually we're writing a work-around to fix a problem of the nullrenderer and by doing this we sacrifice the `attach` feature and maybe more. I'd be happier if Klei could fix this issue in their code, so we don't have to work around it. I'll think about contacting them to see what they say about it.

Anyway, if we get this running in a satisfying way, we can still merge it for now - I don't think it's the best solution, but if it works, it is what we need.

**Comment by BraisGabin** [comment]
This PR is outdated. I'll send a new one with the "no stale" parts.

**Pull request closed without merging**
