### PR TITLE
Upgrade to version 0.3 of the steamcmd base-image

### PR DESCRIPTION
**Pull request by thasmo**

### CODE REVIEW

**Comment by thasmo** [comment]
Weird. Any idea what this is caused by? I think this didn't happen with Debian 8.
```sh
Running close-cleanly [5/16]
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"kill\": executable file not found in $PATH"
[FAIL] close-cleanly
```

**Comment by BraisGabin** [comment]
Yes, really weird... I'll check it this night. It didn't find the `kill` command O_o

**Comment by BraisGabin** [comment]
I think that I found the problem... and the problem is the test. It doesn't work before. But it just silently
Really strange... 
```
docker exec -it container kill 1
```
doesn't work but
```
docker exec -it container bash
kill 1
```
works perfectly...

Probably we can't use `exec` with `kill`...

**Comment by thasmo** [comment]
Do we have to kill it at all?

**Review by BraisGabin — DISMISSED** [review]

**Review by BraisGabin — APPROVED** [review]

**Pull request merged**
