### PR TITLE
Bats

### LINKED ISSUE #100: Make the test-suite fly
Not high priority, but it would be nice to find ways to make the test-suite take less time to complete. Tests should run as fast as possible and tests which use `sleep` to wait for certain tasks may be refactored to complete as fast as possible.

### PR DESCRIPTION
**Pull request by BraisGabin**
Move tests from our custom framework to bats.

Closes #100

### CODE REVIEW

**Comment by BraisGabin** [comment]
The suite flies now! 6 minutes 🎉.

**Comment by thasmo** [comment]
You're the best! So awesome! 🥇

**Comment by BraisGabin** [comment]
All tests moved to bats 🎉

**Comment by thasmo** [comment]
@BraisGabin This is ready to be merged, right?

**Comment by BraisGabin** [comment]
Right

**Review by thasmo — APPROVED** [review]

**Comment by thasmo** [comment]
Awesome work, this is really great! Thanks @BraisGabin! 😄

**Pull request merged**
